# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cert1', models.CharField(blank=True, max_length=200)),
                ('Cert2', models.CharField(blank=True, max_length=200)),
                ('Cert3', models.CharField(blank=True, max_length=200)),
                ('Cert4', models.CharField(blank=True, max_length=200)),
                ('Cert5', models.CharField(blank=True, max_length=200)),
                ('Cert6', models.CharField(blank=True, max_length=200)),
                ('Cert7', models.CharField(blank=True, max_length=200)),
                ('Cert8', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dates', models.CharField(blank=True, max_length=100)),
                ('Academy', models.CharField(blank=True, max_length=200)),
                ('Degree', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lang1', models.CharField(blank=True, max_length=100)),
                ('Lang2', models.CharField(blank=True, max_length=100)),
                ('Lang3', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skill1', models.CharField(blank=True, max_length=255)),
                ('Skill2', models.CharField(blank=True, max_length=255)),
                ('Skill3', models.CharField(blank=True, max_length=255)),
                ('Skill4', models.CharField(blank=True, max_length=255)),
                ('Skill5', models.CharField(blank=True, max_length=255)),
                ('Skill6', models.CharField(blank=True, max_length=255)),
                ('Skill7', models.CharField(blank=True, max_length=255)),
                ('Skill8', models.CharField(blank=True, max_length=255)),
                ('Skill9', models.CharField(blank=True, max_length=255)),
                ('Skill10', models.CharField(blank=True, max_length=255)),
                ('Skill11', models.CharField(blank=True, max_length=255)),
                ('Skill12', models.CharField(blank=True, max_length=255)),
                ('Skill13', models.CharField(blank=True, max_length=255)),
                ('Skill14', models.CharField(blank=True, max_length=255)),
                ('Skill15', models.CharField(blank=True, max_length=255)),
                ('Skill16', models.CharField(blank=True, max_length=255)),
                ('Skill17', models.CharField(blank=True, max_length=255)),
                ('Skill18', models.CharField(blank=True, max_length=255)),
                ('Skill19', models.CharField(blank=True, max_length=255)),
                ('Skill20', models.CharField(blank=True, max_length=255)),
                ('Skill21', models.CharField(blank=True, max_length=255)),
                ('Skill22', models.CharField(blank=True, max_length=255)),
                ('Skill23', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Position', models.CharField(blank=True, max_length=100)),
                ('Address', models.CharField(blank=True, max_length=255)),
                ('Email', models.CharField(blank=True, max_length=100)),
                ('Tel', models.CharField(blank=True, max_length=100)),
                ('Photo', models.ImageField(blank=True, upload_to='static/images')),
                ('LinkedIn', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date1', models.CharField(blank=True, max_length=100)),
                ('Work1', models.CharField(blank=True, max_length=100)),
                ('Position1', models.CharField(blank=True, max_length=200)),
                ('Date2', models.CharField(blank=True, max_length=100)),
                ('Work2', models.CharField(blank=True, max_length=100)),
                ('Position2', models.CharField(blank=True, max_length=200)),
                ('Date3', models.CharField(blank=True, max_length=100)),
                ('Work3', models.CharField(blank=True, max_length=100)),
                ('Position3', models.CharField(blank=True, max_length=200)),
                ('Date4', models.CharField(blank=True, max_length=100)),
                ('Work4', models.CharField(blank=True, max_length=100)),
                ('Position4', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
